<?php get_header(); ?>
<!-- disini yang per page -->
<section id="pg">
    <img id="texture" src="http://brawijayafilmfest.com/wp-content/uploads/2022/06/Layer-4.png" alt="texture">
    <div class="wrapper">
        <h2>Rules & Regulation</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis et molestiae quam adipisci temporibus commodi vero assumenda laborum recusandae ipsum illum quisquam, nam minus molestias totam omnis vel, deserunt qui. Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus fugit placeat dicta perspiciatis cupiditate dolores harum inventore non porro voluptatum. Consectetur unde ab quidem exercitationem laboriosam quo debitis quibusdam molestias? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sapiente, maxime distinctio nam consectetur non quibusdam quo quisquam incidunt quia numquam officiis a voluptatibus est. Delectus mollitia velit quia. Corrupti, debitis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Alias ipsum, eaque officia, obcaecati pariatur eveniet provident voluptatibus deleniti fuga deserunt distinctio, dicta rem velit. Vitae sed sit cumque quaerat quasi Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa officia ducimus quasi aspernatur obcaecati dolores deserunt eius. Voluptatem, odit ipsa reprehenderit officiis doloremque odio, praesentium enim incidunt modi, consequatur quo. Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis tempora enim explicabo possimus blanditiis voluptas quasi quibusdam debitis qui excepturi, culpa quia natus rerum amet placeat molestias sequi beatae sapiente. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minima sunt consectetur eius voluptatum eos delectus natus dolorem! Ducimus deleniti architecto ratione nisi recusandae hic possimus impedit sunt, facere, doloribus molestiae? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sunt saepe laborum minus nostrum quis explicabo. Incidunt eveniet libero rerum distinctio illo atque doloribus dicta sunt excepturi dolorum? Vel, consequatur. Commodi?Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro aliquid accusantium eos velit reprehenderit exercitationem quas officia dignissimos obcaecati, quibusdam voluptatem vel nihil iste ex mollitia sapiente assumenda? Beatae, ipsam! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minima porro magnam, tenetur esse facilis non tempore ducimus ipsam laboriosam cumque reprehenderit sit odit, sapiente hic quidem sed excepturi quis? Exercitationem. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam, laboriosam totam quos natus id corrupti eligendi ullam facere odit iure, repudiandae incidunt corporis velit quas quam reprehenderit distinctio voluptates. Nisi. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestiae laborum doloremque repellat voluptas quam quis nulla, nemo maxime deserunt eos unde earum ipsa temporibus accusantium rem error, velit non dolorum. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit quod dolore mollitia amet repellat nostrum fugiat. Numquam hic illo dolore. Sint, ratione! Quae at amet qui corporis quasi, saepe atque?</p>
    </div>
</section>

<!-- sampai sini -->
<?php get_footer(); ?>
